version: '3.8'

services:
  django-backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  react-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
